config/routes.rb
SampleApp::Application.routes.draw do  

  resources :candidates_profiles


  get "email/remind"

  post "email/remind"

  resources :admin_users

  resources :candidates do
    member do
      get :following, :followers, :change, :index
      post :change
    end
    collection do
      get 'search'
    end

  end

  resources :pages do
    collection do
      get 'search'
    end
  end
  
  resources :ExportExcel  
  
  resources :candidates do
    resources :candidate_certifications
    resources :candidate_profiles
    resources :candidate_profile_tags
  end

  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :reply, :update, :feed_micropost, :destroy]
  
  resources :followings do
    collection do 
       post  'follow'
    end
  end

  resources :resume
  resources :candidate_prof_summaries do
    collection do
      get 'destroy'
      post 'destroy'
    end
  end

  resources :candidate_certifications do
    collection do
      get 'destroy'
      post 'destroy'
    end
  end

  match "admin_users/:id/edit/:role" => 'admin_users#edit'
  match "admin_users/new/:letra" => 'admin_users#new'
  match "admin_users/:id/add" => 'admin_users#add'
  match "admin_users/search/:txt" => 'admin_users#search'

  match '/signup',  :to => 'candidates#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'

  match "/candidates/:id/followings" => 'followings#follow'
  match "/candidates/:id/unfollow" => 'followings#destroy'
  #match "/candidates/:id/microposts" => 'microposts#create'

  match "/reply/:id" => 'microposts#reply'
  match "/reply" => 'microposts#reply'
  match "/microposts/:id" => 'microposts#update'
  match "/feed_admin/:id" => 'microposts#feed_micropost'

  match "/candidates/:id/resume" => 'resume#index'
  match "/candidates/:id/resume/staff_update" => 'resume#staff_update'
  match "/candidates/:id/resume/summary" => 'resume#summary'
  match "/candidates/:id/resume/experience" => 'resume#experience'
  match "/candidates/:id/resume/experience/new" => 'experiences#new'
  match "/candidates/:id/resume/experience/:experience_id/skills/new" => 'experiences#skill'
  match "/experiences/:id/destroy" => 'experiences#destroy'
  match "/candidates/:id/resume/experience/:experience_id/details/new" => 'experience_details#new'
  #match "/resume_details/:id/destro" => 'resume_details#destro'
  match "/candidate_prof_summaries/destro" => 'candidate_prof_summaries#destro'
  #match "/resume_details/:id/destroy" => resume_details_destroy_path
#  match "/candidates/:id/resume/education" => 'resume#education'
#  match "/education/destroy" => 'educations#destroy'
  # Projects
  match "/candidates/:id/projects" => 'projects#index'
  match "/candidates/:id/projects/new" => 'projects#new'
  match "/candidates/:id/project/:project_id/update" => 'projects#update'
  match "/candidates/:id/project/:project_id/show" => 'projects#show'
  match "/candidates/:id/project/:project_id/destroy" => 'projects#destroy'
  ## Project Roles
  match "/candidates/:id/project/:project_id/projects_roles/new" => 'projects_roles#new'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/update" => 'projects_roles#update'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/show" => 'projects_roles#show'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/destroy" => 'projects_roles#destroy'
  ## Project Responsibilities
  match "/candidates/:id/projects/:project_id/projects_roles/:projects_role_id/roles_responsibilities/new" => 'roles_responsibilities#new'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/roles_responsibilities/:rolerespon_id/destroy" => 'roles_responsibilities#destroy'
  ## Project Tags
  match "/candidates/:id/projects/:project_id/projects_roles/:projects_role_id/projects_tags/:type_id/new" => 'projects_tags#new'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/projects_tags/:projtag_id/destroy" => 'projects_tags#destroy'
  # Education
  match "/education/:id" => 'education#index', :as => :candidate_education
  match "/education/destroy" => 'candidate_education#destroy'
  match "/candidates/:id/resume/education" => 'candidate_education#index'
  match "/candidates/:id/resume/education/new" => 'candidate_education#new'
  match "/candidates/:id/resume/education/create" => 'candidate_education#create', :as => :candidate_education_index
  match "/candidates/:id/resume/education/edit" => 'candidate_education#edit'
  match "/candidates/:id/resume/education/update" => 'candidate_education#update'
  match "/candidates/:id/resume/education/destroy" => 'candidate_education#destroy'
  match "/candidates/:id/education_degree" => 'educ_degree#index'
  match "/candidates/:id/education_degree/new" => 'educ_degree#new'
  match "/candidates/:id/education_degree/create" => 'educ_degree#create'
  match "/candidates/:id/education_degree/edit" => 'educ_degree#edit'
  match "/candidates/:id/education_degree/update" => 'educ_degree#update'
  match "/candidates/:id/education_degree/destroy" => 'educ_degree#destroy'
  match "/candidates/:id/education_degree/action" => 'educ_degree#action'

  match "/candidates/:id/candidate_certifications/new" => 'candidate_certifications#new'

  # Candidate
  match "/staff/:id/candidates" => 'staff_candidates#index'
  match "/staff/:id/candidates/detail" => 'staff_candidates#search'

  # Candidate Status
  match "/staff/:id/candidate_status" => 'status#index'
  match "/staff/:id/candidate_status/create" => 'status#create'
  match "/staff/:id/candidate_status/destroy" => 'status#destroy'

  # Interviewers
  match "/staff/:id/interviewers" => 'interviewers#index'
  match "/staff/:id/interviewers/new" => 'interviewers#new'
  match "/staff/:id/interviewers/:interviewer_id/edit" => 'interviewers#edit'
  match "/staff/:id/interviewers/:interviewer_id/delete" => 'interviewers#delete'
    
  # Candidate Certification
  match "/candidates/:id/certification" => 'candidate_certification#index'
  #match "/candidates/:id/resume/certification/new" => 'candidate_certification#new'
  match "/candidate_certifications/destro" => 'candidate_certifications#destro'
  #match "/resume_details/destro" => 'resume_details#destro'
  
  # Certifications
  match "/staff/:id/certifications" => 'certifications#index'
  match "/staff/:id/certifications/action" => 'certifications#action'
  match "/staff/:id/certifications/new" => 'certifications#new'
  match "/staff/:id/certifications/:certification_id/edit" => 'certifications#edit'
  match "/staff/:id/certifications/:certification_id/delete" => 'certifications#delete'
  
  # Roles
  match "/staff/:id/roles" => 'roles#index'
  match "/staff/:id/roles/action" => 'roles#action'
  match "/staff/:id/roles/new" => 'roles#new'
  match "/staff/:id/roles/:role_id/edit" => 'roles#edit'
  match "/staff/:id/roles/:role_id/delete" => 'roles#delete'
  
  # Trainings
  match "/candidates/:id/resume/training" => 'candidate_training#index'
  match "/candidates/resume/training/new" => 'candidate_training#new'
  match "/training/destroy" => 'candidate_training#destroy'
  # Languages
  match "/candidates/:id/resume/languages" => 'candidate_languages#index'
  match "/candidates/resume/languages/new" => 'candidate_languages#new'
  match "/candidates/:id/resume/:candidate_language/languages/edit" => 'candidate_languages#edit'  
  match "/languages/destroy" => 'candidate_languages#destroy'
  match "/staff/:id/languages" => 'languages#index'
  match "/staff/:id/languages/new" => 'languages#new'
  match "/staff/:id/languages/create" => 'languages#create'
  match "/staff/:id/languages/action" => 'languages#action'

  # Tags
  match "/staff/:id/tags" => 'tags#index'
  match "/staff/:id/tags/new" => 'tags#new'
  match "/staff/:id/tags/create" => 'tags#create'
  match "/staff/:id/tags/edit" => 'tags#edit'
  match "/staff/:id/tags/update" => 'tags#update'
  match "/staff/:id/tags/destroy" => 'tags#destroy'
  match "/staff/:id/tags/action" => 'tags#action'

  # Report
  match "/staff/:id/report" => 'report#index'
  match "/staff/:id/report/search" => 'report#search'
 

  # Autocomplete
  match "/tool/autocomplete" => 'tool_tag#autocomplete'
  match "/tech/autocomplete" => 'technology_tag#autocomplete'
  match "/know/autocomplete" => 'knowledge_tag#autocomplete'

  match '/skills', :to => 'skills#index'
  match '/skills/new', :to => 'skills#new'
  
  # Candidates Interviews
  match "/candidates/:id/candidates_interviews" => 'candidates_interviews#index'
  match "/candidates/:id/candidates_interviews/:cand_inter_id/edit" => 'candidates_interviews#edit'
  match "/candidates/:id/candidates_interviews/new" => 'candidates_interviews#new'
  match "/candidates/:id/candidates_interviews/:cand_inter_id/delete" => 'candidates_interviews#delete'
  ## Interviews Type
  match "/staff/:id/interviews_types" => 'interviews_types#index'
  match "/staff/:id/interviews_types/new" => 'interviews_types#new'
  match "/staff/:id/interviews_types/:interview_type_id/edit" => 'interviews_types#edit'
  match "/staff/:id/interviews_types/:interview_type_id/delete" => 'interviews_types#delete'
  
  ## Candidates Profiles
  match "/candidates/:candidate_id/candidate_profiles" => 'candidate_profiles#index'
  match "/candidates/:candidate_id/candidate_profiles/:candidate_profile_id/delete" => 'candidate_profiles#delete'
  match "/candidates/:candidate_id/candidate_profiles/:candidate_profile_id/edit" => 'candidate_profiles#edit'
  match "/candidates/:candidate_id/candidate_profiles/:candidate_profile_id/update" => 'candidate_profiles#update'
  match "/candidates/:candidate_id/candidate_profiles/:candidate_profile_id" => 'candidate_profiles#update'

app/views/shared/_admin_feed.html.haml
- unless @page_results2.empty?
  Candidate Following:
  %br
  %br
  = label_tag "Show only my conversations with selected candidate"
  = check_box_tag "onlyMyPosts"
  %br
  %br
  = select_tag "select_follower", options_for_select(@page_results2.collect{ |u| [(u.first_name + " " + u.first_last_name), u.id] }), :prompt => "Select a Candidate"

app/views/shared/_admin_sidebar_signed.html.haml
#sidebar
  <!-- Subnav -->
  %h4#if_sub_nav
    Profile Information
  #if_subnav.divider
    - if signed_in?
      #sidebar-profile
        #sidebar-gravatar
          =link_to("#") do
            = image_tag @candidate.avatarurl
        #sidebar-candidate
          = @candidate.first_name
          = @candidate.first_last_name
      %br
    %br
    -if !['Admin', 'Super Admin'].include?( get_user_type )
      
      %ul#nav_sub.sub_navigation
        %li
          %i.iconContact-info
          = link_to 'Profile', edit_candidate_path(current_candidate), :class => "profile-sub_navigation"
        %li
          %i.iconResume
          = link_to_candidates('Candidates', current_candidate.id, :action => 'candidates', :class => 'profile-sub_navigation')
        %li
          %i.iconReport
          = link_to 'Advanced search', '/staff/' + current_candidate.id.to_s() + '/report', :class => 'profile-sub_navigation'
        %li
          %i.iconSummary
            = label_tag 'Catalogs', nil, :class => 'profile-sub_navigation'
          %br
          %br
          %ul#nav_sub.sub_navigation
            //%li
            //  %i.iconStatus
            //  = link_to 'Candidate Status', '/staff/' + current_candidate.id.to_s() + '/candidate_status', :class => 'profile-sub_navigation'
            %li
              %i.iconIntervieweType
              = link_to "Interview Types", url_options = { :controller => "interviews_types", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconInterviewer
              = link_to "Interviewers", url_options = { :controller => "interviewers", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconEducation
              = link_to_resume('Education Degrees', current_candidate.id, :action => 'educ_degree', :class => 'profile-sub_navigation')
            %li
              %i.iconInterests
              = link_to 'Languages', '/staff/' + current_candidate.id.to_s() + '/languages', :class => 'profile-sub_navigation'
            %li
              %i.iconCertification
              = link_to "Certifications", url_options = { :controller => "certifications", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconRolesHeadLine{:style => 'margin-top: 8px;'}
              = link_to "Roles", url_options = { :controller => "roles", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconTags
              = link_to "Tags", url_options = { :controller => "tags", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
    -else
      %ul#nav_sub.sub_navigation

        // - if is_follow?(@candidate.id)
        = link_to('send Message', '#', html_options = {:id => "send_message", :class=>"show_hide", :rel=>"#slidingDiv"})
        %div#slidingDiv
          = form_for(:microposts, :url=>{:controller => "microposts", :action=>'create'}, :html => {:id => "createMicroPostForm"}) do |f|
            = hidden_field_tag :candidate_id , @candidate.id
            = text_area_tag "message_text"
            = submit_tag "Send", :class => "btn-primary"
        %div#emptyDiv
        %br
        %br
        = link_to 'Return Home', edit_candidate_path(current_candidate), :class => "profile-sub_navigation"
        %h4 "Edit as #{current_candidate.first_name} #{current_candidate.first_last_name}" 
        %li
          %i.iconContact-info
          = link_to 'Profile', edit_candidate_path(@candidate), :class => "profile-sub_navigation"
        %li
          %i.iconResume
          = link_to_resume('Resume', @candidate.id, :action => 'resume', :class => 'profile-sub_navigation')
          %ul#nav_sub.sub_navigation
            %li
              %i.iconSummary
              = link_to_resume('Summary', @candidate.id, :action => 'summary', :class => 'profile-sub_navigation')
            %li
              %i.iconExperience
              = link_to_project('Projects', @candidate.id, :action => 'index', :class => 'profile-sub_navigation')
            %li
              %i.iconEducation
              = link_to_resume('Education', @candidate.id, :action => 'education', :class => 'profile-sub_navigation')
            %li
              %i.iconCertification
              = link_to_resume('Certification', @candidate.id, :action => 'certification', :class => 'profile-sub_navigation')
            %li
              %i.iconExperience
              = link_to_resume('Candidate Profiles', @candidate.id, :action => 'candidate_profiles', :class => 'profile-sub_navigation')
            %li.last
              %i.iconInterests
              = link_to_resume('Languages', @candidate.id, :action => 'languages', :class => 'profile-sub_navigation')
    %br
    .clear

app/views/shared/_error_messages.html.erb
<% if @error.any? %> 
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %> 
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h2>
    <p>There were problems with the following fields:</p> 
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> 
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.haml
- unless @error.nil?
  - if @error.any?
    #error_explanation
      %h2
        = pluralize(object.errors.count, "error")
        prohibited this 
        = object.class.to_s.underscore.humanize.downcase
        from being saved:
      %p 
        There were problems with the following fields: 
        %ul
          - object.errors.full_messages.each do |msg| 
            %li= msg

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %> 
  </td>
  <td class="micropost"> 
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %> 
    </span>
    <span class="content">
      <%= feed_item.content %>
    </span> 
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago. 
    </span>
  </td>
  <% if current_user?(feed_item.user) %> 
  <td class="micropost-delete">
    	<%= link_to "delete", feed_item, :method => :delete, :confirm => "You sure?", :title => feed_item.content %>								
  </td>
  <% end %> 
</tr>

app/views/shared/_feed_item.html.haml
%tr.feed-content
  - admin_candidate = Candidate.find(feed_item.created_by)
  %td.gravatar
    = link_to gravatar_for(admin_candidate), admin_candidate 
  %td.micropost 
    %span(class='candidate')
      = link_to admin_candidate.first_name, admin_candidate 
    %span(class='content')
      = feed_item.content
    %span(class='timestamp')
      Posted 
      = time_ago_in_words(feed_item.created_at)
      ago.
  %td.micropost-delete
    - @value = "/reply/#{feed_item.created_by}"
    = label_tag :reply, t("reply"), :id => "#{feed_item.created_by}", :class=>"show_hide", :rel=>"#slidingDiv2"
    - if (current_candidate.id == feed_item.created_by)
      = link_to "Remove", feed_item, :method => :update, :confirm => "You sure?", :title => feed_item.content



  

app/views/shared/_micropost_form.html.erb
<% form_for(@micropost, :html => { :class => "micropost_form"} ) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
    <%= f.text_area :content %> 
    <%= f.submit "Submit" %>
<% end %>

app/views/shared/_micropost_form.html.haml
- form_for(@micropost, :html => { :class => "micropost_form"} ) do |f|
  = render 'shared/error_messages', :object => f.object
  = f.text_area :content
  = f.submit "Submit"

app/views/shared/_projects.html.haml
<!-- Content -->      
#content
  - if !signed_in?
    %img(src='http://www.4thsource.com//public/images/subheader_services.jpg' class='subheader' alt='Sub Header')
  %ul#breadcrumbs
    %li
      = link_to 'Home', root_path 
      = raw '&raquo;'
    %li
      = link_to_resume("My profile", @candidate.id, :action => "resume")
      = raw '&raquo;'
    %li= raw('<em>Projects</em>')
    .clear
  %h3.page_headline 
    %i.iconExperienceHeadLine
    .h3-page-headline
      Projects
  .divider-headline
  %br
  #flash
    - flash.each do |key, value|
      .flash{:class => key}= value
  %br
  =link_to_project("Add Project", @candidate.id, :action => "new")
  %br
  %br
  - if @projects_items.count > 0
    %br
    - @projects_items.each do |project|
      %br
      .project_left
        %h6= project.company_name
        %h6= project.name
      .project_right
        = link_to "Edit", :controller => "projects", :action => "show", id:@candidate.id, :project_id=> project.id
        &nbsp;&nbsp;&nbsp;
        
        = link_to "Delete", url_options = { :controller => "projects", :action => "destroy", id:@candidate.id, :project_id=> project.id }, html_options = { :confirm => "Are you sure?" }
      %br
      #project-description
        = project.summary
      - if project.projroles.count > 0
        %list
          - project.projroles.each do |role|
            #row
              %i.iconRolesHeadLine
              .project_role_left
                %h6
                  = Role.find_by_id(role.roles_id).name
              .divider-headline
              .project_role_right
                = Date::MONTHNAMES[role.date_in.month]
                = role.date_in.year
                = raw(' - ')
                = Date::MONTHNAMES[role.date_out.month]
                = role.date_out.year
              %br
              %i.iconResponsibilitiesHeadLine
              .responsibility_left
                %h6
                  Responsibilities
              - if role.roles_responsibilities.count > 0
                - role.roles_responsibilities.each do |respon|
                  .responsibility_left
                    %il
                      = respon.description
              - else
                &nbsp;----
              %br
              %br
              %i.iconTechnologyHeadLine
              .tag_left
                %h6
                  Technologies
              %br 
              - if role.tags3.count > 0
                - role.tags3.each do |pt|
                  %il
                    .tag_left
                      %strong
                        = Tag.find(pt.tags_id).name
                      &nbsp;&bull;
                      = pt.description
                    .tag_right
                      = Date::MONTHNAMES[pt.date_in.month]
                      = pt.date_in.year
                      = raw(' - ')
                      = Date::MONTHNAMES[pt.date_out.month]
                      = pt.date_out.year 
              - else
                .tag_left
                  &nbsp;----
              %br
              %br
              %i.iconKnowledgeHeadLine
              .tag_left
                %h6
                  Knowledges
              %br 
              - if role.tags2.count > 0
                - role.tags2.each do |pt|
                  %il
                    .tag_left
                      %strong
                        = Tag.find(pt.tags_id).name
                      &nbsp;&bull;
                      = pt.description
                    .tag_right
                      = Date::MONTHNAMES[pt.date_in.month]
                      = pt.date_in.year
                      = raw(' - ')
                      = Date::MONTHNAMES[pt.date_out.month]
                      = pt.date_out.year
              - else
                .tag_left
                  &nbsp;----
              %br
              %br
              %i.iconToolHeadLine
              .tag_left
                %h6
                  Tools
              %br 
              - if role.tags1.count > 0
                - role.tags1.each do |pt|
                  %il
                    .tag_left
                      %h6
                        = Tag.find(pt.tags_id).name
                    .tag_right
                      = Date::MONTHNAMES[pt.date_in.month]
                      = pt.date_in.year
                      = raw(' - ')
                      = Date::MONTHNAMES[pt.date_out.month]
                      = pt.date_out.year 
                    .tag_left
                      = pt.description
              - else
                .tag_left
                  &nbsp;----
              %br
              %br
      - else
        .experience_details_wrapper
        .experience_details_left
          Please create at least one role.  
      %br
      %br
  - else
    %h4 Please create at least one project.
    .divider
  %br
  .clear
<!-- Sidebar -->
= render 'shared/sidebar_signed'

app/views/shared/_sidebar.html.haml
<!-- Sidebar -->
#sidebar
  <!-- Subnav -->
  %h4#if_sub_nav
    = link_to 'About', '#'
  #if_subnav.divider
  %ul#nav_sub.sub_navigation
    %li= link_to 'Corporate Overview', '#'
    %li= link_to 'Clients', '#'
    %li.last= link_to 'Executive Leadership', '#'
  %img(src="http://www.4thsource.com//public/images/sidebar_about.jpg" alt="about" class="sidebar_img")
  .clear

app/views/shared/_sidebar_signed.html.haml
#sidebar
  <!-- Subnav -->
  %h4#if_sub_nav
    Profile Information
  #if_subnav.divider
    - if signed_in?
      #sidebar-profile
        #sidebar-gravatar
          =link_to("#") do
            = image_tag current_candidate.avatar.url(:thumb) || "/images/4thsource_avatar.jpg"
        #sidebar-candidate
          = current_candidate.first_name
          = current_candidate.first_last_name
          %br
      %br
    %br
    -if ['Admin', 'Super Admin'].include?( get_user_type ) #current_candidate.admin_flag
      %ul#nav_sub.sub_navigation
        %li
          %i.iconContact-info
          = link_to 'Profile', edit_candidate_path(current_candidate), :class => "profile-sub_navigation"
        %li
          %i.iconResume
          = link_to_candidates('Candidates', current_candidate.id, :action => 'candidates', :class => 'profile-sub_navigation')
        -if role == SessionsHelper::SUPERADMIN
          %li
            %i.iconAdminUser
            //= link_to 'Admin users', 'admin_users', :class => 'profile-sub_navigation'
            = link_to 'Admin users', '/admin_users', html_options = { :class => 'profile-sub_navigation' }
        %li
          %i.iconReport
          = link_to 'Advanced search', '/staff/' + current_candidate.id.to_s() + '/report', :class => 'profile-sub_navigation'
        %li
          %i.iconSummary
            = label_tag 'Catalogs', nil, :class => 'profile-sub_navigation'
          %br
          %br
          %ul#nav_sub.sub_navigation
            //%li
            //  %i.iconStatus
            //  = link_to 'Candidate Status', '/staff/' + current_candidate.id.to_s() + '/candidate_status', :class => 'profile-sub_navigation'
            %li
              %i.iconIntervieweType
              = link_to "Interview Types", url_options = { :controller => "interviews_types", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconInterviewer
              = link_to "Interviewers", url_options = { :controller => "interviewers", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconEducation
              = link_to_resume('Education Degrees', current_candidate.id, :action => 'educ_degree', :class => 'profile-sub_navigation')
            %li
              %i.iconInterests
              = link_to 'Languages', '/staff/' + current_candidate.id.to_s() + '/languages', :class => 'profile-sub_navigation'
            %li
              %i.iconCertification
              = link_to "Certifications", url_options = { :controller => "certifications", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconRolesHeadLine{:style => 'margin-top: 8px;'}
              = link_to "Roles", url_options = { :controller => "roles", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconTags
              = link_to "Tags", url_options = { :controller => "tags", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
    -else
      %ul#nav_sub.sub_navigation
        %li
          %i.iconContact-info
          = link_to 'Profile', edit_candidate_path(current_candidate), :class => "profile-sub_navigation"
        %li
          %i.iconResume
          = link_to_resume('Resume', current_candidate.id, :action => 'resume', :class => 'profile-sub_navigation')
          %ul#nav_sub.sub_navigation
            %li
              %i.iconSummary
              = link_to_resume('Summary', current_candidate.id, :action => 'summary', :class => 'profile-sub_navigation')
            %li
              %i.iconExperience
              = link_to_project('Projects', current_candidate.id, :action => 'index', :class => 'profile-sub_navigation')
            %li
              %i.iconEducation
              = link_to_resume('Education', current_candidate.id, :action => 'education', :class => 'profile-sub_navigation')
            %li
              %i.iconCertification
              = link_to_resume('Certification', current_candidate.id, :action => 'certification', :class => 'profile-sub_navigation')
            %li
              %i.iconExperience
              = link_to_resume('Candidate Profiles', current_candidate.id, :action => 'candidate_profiles', :class => 'profile-sub_navigation')
            %li.last
              %i.iconInterests
              = link_to_resume('Languages', current_candidate.id, :action => 'languages', :class => 'profile-sub_navigation')
    %br
    .clear

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, :size => 30 %> 
  <span class="user_name">
    <%= current_user.name %> 
  </span>
  <span class="microposts">
    <%= pluralize(current_user.microposts.count, "micropost") %>
  </span>
  </a>
</div>

app/views/shared/_user_info.html.haml
#candidate_info
  =link_to = candidate_path(current_candidate) do
    = gravatar_for current_candidate, :size => 30 
    %span(class="candidate_name")
      = current_candidate.name  
    %span(class="microposts")
      = pluralize(current_candidate.microposts.count, "micropost")

app/views/shared/follower_feed.html.haml
-@page_results.each do |a|
  = label_tag a.content